---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install tools
        run: sudo apt-get update -y && sudo apt-get install -y genisoimage gnu-efi mtools ninja-build
      - name: Configure
        run: cmake -B ${{github.workspace}}/build -G Ninja -DWITH_GOP=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}
      - name: Upload artifacts
        uses: 'actions/upload-artifact@v7'
        with:
          if-no-files-found: error
          name: hello-world-efi-${{ matrix.build-type }}
          path: |
            ${{github.workspace}}/build/hello.efi
            ${{github.workspace}}/build/hello.iso
      - name: Attest
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: |
            ${{github.workspace}}/build/hello.efi
            ${{github.workspace}}/build/hello.iso
      - if: ${{ github.ref_type == 'tag' && matrix.build-type == 'Release' }}
        name: Stage versioned release assets
        run: |
          cp build/hello.efi build/hello-world-efi-${{ github.ref_name }}.efi
          cp build/hello.iso build/hello-world-efi-${{ github.ref_name }}.iso
      - if: ${{ github.ref_type == 'tag' && matrix.build-type == 'Release' }}
        name: Upload package
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            ${{github.workspace}}/build/hello-world-efi-${{ github.ref_name }}.efi
            ${{github.workspace}}/build/hello-world-efi-${{ github.ref_name }}.iso
    strategy:
      matrix:
        build-type: [Debug, Release]
name: Build
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
permissions:
  attestations: write
  contents: write
  id-token: write
