---
jobs:
  build:
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - name: Install tools
        run: pipx install cpp-coveralls && sudo add-apt-repository ppa:brandonsnider/cdrtools && sudo apt-get update -y && sudo apt-get install -y gnu-efi libcmocka-dev lcov mkisofs
      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_GOP=ON -DWITH_TESTS=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}
      - name: Run tests
        run: ctest --test-dir ${{github.workspace}}/build
      - name: Generate coverage information
        run: geninfo '--exclude=*/test.c' -b ${{github.workspace}} -o coverage1.info ${{github.workspace}}/build/CMakeFiles/general_tests.dir
      - if: matrix.build-type == 'Debug'
        name: Coveralls
        run: coveralls -i main.c
    strategy:
      matrix:
        build-type: [Debug, Release]
name: Tests
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
