concurrency:
  cancel-in-progress: true
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}'
jobs:
  test:
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    name: 'Tests'
    permissions:
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Install tools
        run: |
          pipx install cpp-coveralls
          sudo apt-get update -y
          sudo apt-get install -y genisoimage gnu-efi libcmocka-dev lcov ninja-build
      - name: Configure
        run: cmake -B "${GITHUB_WORKSPACE}/build" -G Ninja -DWITH_GOP=ON -DWITH_TESTS=ON
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Build
        run: cmake --build "${GITHUB_WORKSPACE}/build" --config "${BUILD_TYPE}"
      - name: Run tests
        run: ctest --test-dir "${GITHUB_WORKSPACE}/build"
      - name: Generate coverage information
        run: geninfo '--exclude=*/test.c' -b "${GITHUB_WORKSPACE}" -o coverage1.info "${GITHUB_WORKSPACE}/build/CMakeFiles/general_tests.dir"
      - if: matrix.build-type == 'Debug'
        name: Coveralls
        run: coveralls -i main.c
    strategy:
      matrix:
        build-type: [Debug, Release]
name: 'Tests'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions: {}
